### ISSUE TITLE
Support element target

### ISSUE THREAD

**Issue by HarelM** [nicky-lenaers/ngx-scroll-to#1]
I'm using `ng2-scroll-to` which seems to be working fine with angular 4 but has a warning for old dependencies of angular 2, which is annoying, also the name is not great.
I wanted to switch to this library but I'm missing a feature:
`scrollableElementSelector` - which defines which element should be scrolled (the container, as apposed to which element to scroll to).
Am I missing something?

**Comment by nicky-lenaers** [comment]
Thank you for your issue. Glad to hear you've found this plugin. So, the way this module works is as follows: 

Internally, `@nicky-lenaers/ngx-scroll-to` searches for the first scrollable parent node it can find in the HTML markup, searching the DOM tree upwards from the element you set the `[ngx-scroll-to]` directive on. It does this **automatically** (in case you're interested, you can see the function [here](https://github.com/nicky-lenaers/ngx-scroll-to/blob/master/src/scroll-to.service.ts#L56)). As of this moment, there's no option to specify a scrollable parent manually, as you suggest.

Do you mind explaining your situation and provide an example of your code? Then, if you still require such functionality, we can discuss development from there and, if needed, I'll be glad to provide this functionality a.s.a.p.!

**Comment by HarelM** [comment]
Well, I have a site that presents a map and I have a legend to this map.
The legend has section and I want that every section the user opens will be scrolled to the top.
This is already working as I said with ng2-scroll-to.
You can see it [here](https://israelhiking.osm.org.il] when pressing on the left "i" button and then pressing the left tab with the word "מקרא" and then any "+" should scroll its content to the top of the screen.
I tried to replace it locally in my dev version but I'm getting the following error:
```
ERROR Error: No provider for ScrollToService!
    at injectionError (core.es5.js:1169)
    at noProviderError (core.es5.js:1207)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._throwOrNull (core.es5.js:2649)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKeyDefault (core.es5.js:2688)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_._getByKey (core.es5.js:2620)
    at ReflectiveInjector_.webpackJsonp.../../../core/@angular/core.es5.js.ReflectiveInjector_.get (core.es5.js:2489)
    at resolveNgModuleDep (core.es5.js:9473)
    at NgModuleRef_.webpackJsonp.../../../core/@angular/core.es5.js.NgModuleRef_.get (core.es5.js:10555)
    at resolveDep (core.es5.js:11058)
    at createClass (core.es5.js:10922)
```
Not sure how to proceed here...
Code can be found [here](https://github.com/IsraelHikingMap/Site)
and the relevant html file is here (you can see the `scrollTo` there):
https://github.com/IsraelHikingMap/Site/blob/master/IsraelHiking.Web/sources/application/components/sidebar/info-sidebar.component.html

**Comment by HarelM** [comment]
Sorry, I miss-configured the module, now I don't have this error but it doesn't scroll the content the way I want...

**Comment by nicky-lenaers** [comment]
Good that your configuration is now correct. Could you explain what exactly is not working? Is your content scrolling or not at all?

**Comment by HarelM** [comment]
I don't see any animation so I'm guessing it doesn't work at all now that you mention it.
This is the code I use:
```
<a class="cursor-pointer" (click)="toggleSectionVisibility(section)" [ngx-scroll-to]="section.id"><h4><i class="fa" [ngClass]="{'icon-plus': !isSectionVisible(section), 'icon-minus': isSectionVisible(section) }"></i> {{section.title}}</h4></a>
```
Which should replace the current line of code:
```
<a class="cursor-pointer" (click)="toggleSectionVisibility(section)" scrollTo scrollTargetSelector="#{{section.id}}" scrollableElementSelector="#sidebar-wrapper"><h4><i class="fa" [ngClass]="{'icon-plus': !isSectionVisible(section), 'icon-minus': isSectionVisible(section) }"></i> {{section.title}}</h4></a>
```

**Comment by nicky-lenaers** [comment]
@HarelM I've testing your case in a Plunkr and notices that nested scrolling to elements does not work (because of [this](https://github.com/nicky-lenaers/ngx-scroll-to/blob/master/src/statics/scroll-to-animation.ts#L70) line). I'm working on a fix as we speak. I'll get you updated when this is working!

**Comment by HarelM** [comment]
Thanks for the quick response and update!! let me know if there's anything I can do to help out.

**Comment by nicky-lenaers** [comment]
@HarelM I've added support for scrolling in nested `div`'s, as well as support for elements originally being hidden by `*ngIf` statements. You'll find both updates in [`0.2.1`](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/0.2.1). See [`CHANGELOG.MD`](https://github.com/nicky-lenaers/ngx-scroll-to/blob/master/CHANGELOG.md) for details.

Also, I've created a Plunker that demonstrates your example, fixed and perfectly working with version `0.2.1` of this module. [Check out the Plunker](https://plnkr.co/edit/ArxQV06PEwA3Vl2nf1gR?p=preview).

Please let me know if this solves your issue.

Thanks!

**Comment by HarelM** [comment]
I'm getting this error now when using the latest version:
```
 TypeError: Cannot read property 'forEach' of undefined
    at new ScrollAnimation (scroll-to-animation.js:37)
    at ScrollToService.webpackJsonp.../../../../@nicky-lenaers/ngx-scroll-to/scroll-to.service.js.ScrollToService.onTrigger (scroll-to.service.js:25)
    at scroll-to.directive.js:37
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
    at Object.onInvokeTask (core.es5.js:3881)
    at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
    at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:191)
    at webpackJsonp.../../../../zone.js/dist/zone.js.ZoneTask.invokeTask (zone.js:498)
    at ZoneTask.invoke (zone.js:487)
    at timer (zone.js:1823)
```

**Comment by HarelM** [comment]
Ignore the error (again) :-/ Issue with npm download and angular compilation.
but it still doesn't work - no animation and no scrolling still with version 0.2.1

**Comment by nicky-lenaers** [comment]
How about the [Plunker](https://plnkr.co/edit/ArxQV06PEwA3Vl2nf1gR?p=preview) I provided, is that working for you? If so, you should be able to mimic this behaviour in your app, right? Also, do you still get any errors?

It's kinda hard for me to debug since I'm not developing your app. Maybe you can set up a minimal Plunker yourself and add just the parts that are relevant for this issue so I can take a look.

**Comment by HarelM** [comment]
Not sure this describes my problem as I see errors in the console in the plunker and I don't see the same errors when I'm running my code but the principle is the same:
Setting the id in the component code.
https://plnkr.co/edit/hGLKh0ofqjDPHQjv1bxd?p=preview
I don't fully understand how this is different from the example you sent, but it doesn't work similarly...

**Comment by nicky-lenaers** [comment]
@HarelM I caught the error, it was because the ID of the element is `0`, which I guess internally get's set to false. I prefixed the ID's with `fold-`, now it works. [See Plunker](https://plnkr.co/edit/abXRoijGa60JzSoOGCwK?p=preview)

**Comment by HarelM** [comment]
I don't think that's it. I changed the component code to start the Id numbering from 1 instead of 0 and it still fails.
Let me know if you can create a plunker that works that uses the variable name without manipulation like I did. (without the `='fold' +...` in the html)

**Comment by nicky-lenaers** [comment]
@HarelM Alright, good feedback! So just for the sake of best practices, I looked it up, for [HTML4](https://www.w3.org/TR/html4/types.html#type-id). From the official docs:

> ID and NAME tokens must begin with a letter ([A-Za-z]) and may be followed by any number of letters, digits ([0-9]), hyphens ("-"), underscores ("_"), colons (":"), and periods (".").

However, from the [HTML5](https://www.w3.org/TR/html5/dom.html#the-id-attribute) docs:

> There are no other restrictions on what form an ID can take; in particular, IDs can consist of just digits, start with a digit, start with an underscore, consist of just punctuation, etc.

So you're right, digits should be supported as values for `id`. I will add a bug for this, research it and fix this soon!

**Comment by HarelM** [comment]
I think I managed to make it work in the plunker example (was missing a {{...}}. I'll see if I can make this work in my code as well...

**Comment by HarelM** [comment]
I had another look at my code and it seems to declare the ids with "_" to avoid this issue.
I can't make a plunker reproduction unfortunately but I can debug the scroll-to code and it gets hit when clicking, it finds a parent to scroll to but it doesn't animate it apparently.
Also the parent it finds is not the parent I want so this issue is still relevant :-)
If you're up to it and willing to help me out here I have publish a version to my test site with your package and you can try and debug why the scrolling does not work, I couldn't fully understand the animation code so I'm not sure how to help.
Site can be found here:
https://israelhiking.osm.org.il/test/
Add a break point in the file called vendor.js
look for `ScrollToDirective`
Here's a screenshot with a break point hit on chrome:
To reproduce: Click the "i" on the right side, click the left tab, click one of the "+" signs.
![image](https://user-images.githubusercontent.com/3269297/28483647-07f24a06-6e77-11e7-8294-70800abbe9a6.png)

Let me know if there's anything else I can do or guide me to the relevant code so I can try debug the relevant part, I feel a bit useless :-(...

**Comment by nicky-lenaers** [comment]
@HarelM You're actually being very helpful so far. Feedback is the most important part of any open source project. You've given me a lot already, so I'm really gald for that.

Now, I took a look at the code in Chrome and stepped through the code like you did earlier. I see, indeed, that the first scrollable parent is incorrect. From what I can tell, the parent that *is* selected actually has an overflow, it's just set to `hidden`. My plugin does not take that into account. I'll create a fix for this and let you know when I'm done.

**Comment by nicky-lenaers** [comment]
@HarelM Ok I made a fix, (in case you're interested, see [this code](https://github.com/nicky-lenaers/ngx-scroll-to/commit/9ccae5b)). This should fix your problem.

Can you let me know if this works for you? If it does not, please don't hesitate to let me know other issues you encounter. Thanks!

**Comment by HarelM** [comment]
It finally works!! :-) thanks a lot!

**Comment by nicky-lenaers** [comment]
You're very much welcome. Keep an eye out for updates as I'll be developing this plugin quiet a lot! You're always welcome to contribute! 👍 Closing this issue.

**Comment by ofermisk** [comment]
Hi there,
First, thanks for the plugin.
I am having a click issue (as far as i know, i am doing all as written :))...
On click i get "Error: No scrollable parent found for element BUTTON".
My code : 
**Template**
<ion-row  >
    <button *ngFor="let item of data" class="chapter_title" [ngx-scroll-to]="item.title">{{item.title}}</button>
  </ion-row> 
  <ion-row *ngFor="let item of data" >
    <ion-card class="cube_white" >
      <ion-card-header>
        <h3>{{item.title}}</h3>
      </ion-card-header>
      <ion-card-content>
        <div id="{{item.title}}">{{item.content}}</div>
      </ion-card-content>
    </ion-card>
  </ion-row>

**The event**
public triggerScrollTo($event: Event, itemIndex) {
    console.log(itemIndex);
    const config: ScrollToConfig = {
      target: itemIndex
    }
    this._scrollToService.scrollTo($event, config);
  }

Please advice...
Thanks for the help

**Comment by nicky-lenaers** [comment]
@ofermisk Thank you for submitting your issue. Do you mind putting this into a seperate issue so I can mark you usecase a specific bug? I'll be able to handle it from there on. On top of my head I'm not sure what's going wrong, but I don't remember testing this inside a `ngFor` loop, so that might be it. I'll be glad to help in a seperate issue.

Thanks.

**Comment by anita-gfm** [comment]
I've implemented this ng2-scroll-to successfully, and works well. It causes a problem with the default scrolling on IOS devices, where the normal page scrolling is not smooth and appears to be sticky.
has anyone else encountered this? And how has this been resolved?

**Comment by nicky-lenaers** [comment]
Hi @anita-gfm, please post your issue in a seperate issue thread as this is already closed. I don't see the relation between your comment and the actual issue.

Thank you for submitting!

**Comment by Jpascual55** [comment]
Hi Anita,
I’ve implemented it too a few days ago and I had the same problem, I dont remember the exact solution but I think I was use something like this: https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/
