### ISSUE TITLE
src directory seems to be missing from NPM package

### ISSUE THREAD

**Issue by Arnaud73** [nicky-lenaers/ngx-scroll-to#101]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Building my Angular 6 app with ngx-scroll-to 1.1 ends with :
<pre>
ERROR in node_modules/@nicky-lenaers/ngx-scroll-to/nicky-lenaers-ngx-scroll-to.d.ts(5,41): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to.directive'.
node_modules/@nicky-lenaers/ngx-scroll-to/public_api.d.ts(1,32): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to.module'.
node_modules/@nicky-lenaers/ngx-scroll-to/public_api.d.ts(2,33): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to.service'.
node_modules/@nicky-lenaers/ngx-scroll-to/public_api.d.ts(3,31): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to-event.interface'.
node_modules/@nicky-lenaers/ngx-scroll-to/public_api.d.ts(4,41): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to-easing.interface'.
node_modules/@nicky-lenaers/ngx-scroll-to/public_api.d.ts(5,58): error TS2307: Cannot find module './src/app/modules/scroll-to/scroll-to-config.interface'.
</pre>

## Environment

<pre><code>
Angular version: 6.1.7

Your version of `@nicky-lenaers/ngx-scroll-to`: 1.1.0

**Comment by paulomonteiro1** [comment]
Same problem.

**Comment by rafa-as** [comment]
Same here

**Comment by nicky-lenaers** [comment]
@Arnaud73 This should be fixed in [version 1.1.1.](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/1.1.1), apologies for the inconvenience (I don't exactly know why this happened). Anyway, could you check?

**Comment by nicky-lenaers** [comment]
Closing this. If this still persists, please let me know!

**Comment by Arnaud73** [comment]
Fixed for me!
Thanks
