### ISSUE TITLE
Make compatible with Angular 7

### ISSUE THREAD

**Issue by Aracturat** [nicky-lenaers/ngx-scroll-to#112]
Please add support of Angular 7

**Comment by nicky-lenaers** [comment]
Thanks for reporting, this is now added in [2.0.0](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/2.0.0).

**Comment by daniel-seitz** [comment]
Any chance this will be available with node version 8?
(I get the error:  @nicky-lenaers/ngx-scroll-to@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.12.0")

**Comment by kondi** [comment]
> Any chance this will be available with node version 8?
> (I get the error: @nicky-lenaers/ngx-scroll-to@2.0.0: The engine "node" is incompatible with this module. Expected version ">=10.0.0". Got "8.12.0")

I already raised this here in December without answer :( : https://github.com/nicky-lenaers/ngx-scroll-to/commit/5b9cb85a65ebd86ed2fc6584f0284f0582b46784#r31667652

**Comment by daniel-seitz** [comment]
@kondi Thanks for pointing this out, that helps narrowing things down. I guess we are all too busy and things sometimes slip through..
