### ISSUE TITLE
Missing ScrollToEvent class in public_api 

### ISSUE THREAD

**Issue by aymebou** [nicky-lenaers/ngx-scroll-to#117]
Hello,

I'm using Angular 7, and added the ngx-scroll-to via:
`$ npm install @nicky-lenaers/ngx-scroll-to`

As I was trying to set the event to wheel, i had the error:
`ERROR in ^^^: error TS2305: Module '"../../../node_modules/@nicky-lenaers/ngx-scroll-to/nicky-lenaers-ngx-scroll-to"' has no exported member 'ScrollToEvent'`

The line raising the error was this one: 
`import { ScrollToAnimationEasing, ScrollToEvent } from '@nicky-lenaers/ngx-scroll-to';`

It appears that the `public_api.d.ts` file is missing the export of the class ScrollToEvent, i don't know why.

I just added `export { ScrollToEvent } from './lib/scroll-to-event.interface';` inside the `public_api.d.ts` file and it worked.

I don't know if this is deliberate or if that was'nt the way I was supposed to do it, but might help others having the same problem or yourself to fix this issue.

Thanks for your module !
aymebou

**Comment by robbertvancaem** [comment]
Hey @aymebou, can you share a code example that I can have a look at? Quite curious to what you're trying to achieve, might indeed be useful to export the ScrollToEvent :-)

**Comment by rafa-as** [comment]
Closed due inactivity
