### ISSUE TITLE
Zoom - wrong position.

### ISSUE THREAD

**Issue by bemiks** [nicky-lenaers/ngx-scroll-to#119]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

After dynamic change of element's size (scroll css property) - scrollTo doesn't properly 'count' the right position.
If I will click the button 2nd time, it goes to the right place.
Offset 0. ScrollTo service.

## Environment

<pre><code>
Angular version: 7.2

Your version of `@nicky-lenaers/ngx-scroll-to`: 2.0

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 

Others:

</code></pre>

**Comment by bemiks** [comment]
Honestly - i've just used a simple js code instead of your library.

const element = document.getElementById('id')
element.scrollIntoView({ behavior: 'smooth', block: 'start' });

**Comment by nicky-lenaers** [comment]
@bemiks Thank you for your comment. I am aware of this, as I marked this repo archived earlier and referred to your solution instead. However, some folks still depended on this lib, so development continued mainly to support newer Angular versions.

I am glad you found a nice and clean solution yourself 👍 .

**Comment by rafa-as** [comment]
Closed due inactivity
