### ISSUE TITLE
iOS doesnt scroll, it jumps to the specified div id.

### ISSUE THREAD

**Issue by Farhan-Islam** [nicky-lenaers/ngx-scroll-to#120]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

On chrome IOS the scroll just jumps to the next div without any scroll event. It just goes straight to the div rather than scrolling up or down to it

## Expected behavior

On chrome IOS the scroll should actually scroll up or down to whatever div id you pass in.

## Minimal reproduction of the problem with instructions

1) Implement an [ngx-scroll-to]="thisIsmeDivId" on an html tag
2) Make sure the elements scrolls as expected in chrome browser on android and desktop
3) Use an iphone device and use latest version of chrome
4) Test the tag by clicking it and see there is no scroll down, but just a screen change to the target div.

## What is the motivation / use case for changing the behavior?

The motivation is so that ios user experience doesnt feel choppy.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular Version 7.0.5

Your version of `@nicky-lenaers/ngx-scroll-to`: v2.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [x ] Chrome (iOS) version 73.0.3683.68
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by rafa-as** [comment]
I just checked that works on Chrome for iOS. Reopen it if you still have this issue.
