### ISSUE TITLE
Having issue with Google Chrome

### ISSUE THREAD

**Issue by cenk1cenk2** [nicky-lenaers/ngx-scroll-to#125]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Unfortunetly does not work with Google Chrome Version >78.0.3904.97 as of my testing. I can get it to work with Microsoft Edge. But could not manage to make it work while I am using the desktop as well as the mobile browser. It does not throw out any errors.

Offset behaviour works without defining any target div but can not perform the same action with a target div.

## Environment

<pre><code>
Angular version: 8.2

Your version of `@nicky-lenaers/ngx-scroll-to`:

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [X ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by kjavia** [comment]
That's because in Chrome you need to give `#id` not just `id` in the `target` property.
