### ISSUE TITLE
9.0.0 release broken in IE11

### ISSUE THREAD

**Issue by pburkindine** [nicky-lenaers/ngx-scroll-to#131]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

In IE11 using ngx-scroll-to 9.0.0, upon navigating to a page, clicks in the scrollbar result in the page immediately jumping back to the top.  Mouse wheel/trackpad scroll works, and after "breaking the seal" with wheel/trackpad the scroll bar begins to work.  Reloading the page will also allow the scroll bar to work.

Reverting ngx-scroll-to to 3.0.1 fixes the problem

## Expected behavior
Clicks in the scroll bar should not be "canceled"

## Environment

<pre><code>
Angular version: 9.1.7

Your version of `@nicky-lenaers/ngx-scroll-to`: 9.0.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [X] IE version 11
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by pburkindine** [comment]
@nicky-lenaers This is blocking our ability to update, is there a chance of a resolution?

**Comment by rbalet** [comment]
@pburkindine It wont be possible since angular & the world is dropping support for IE11. Can you close this issue ?

**Comment by rafa-as** [comment]
Closed due inactivity
