### ISSUE TITLE
How to listen / subscribe to animation finished

### ISSUE THREAD

**Issue by tenglongroy** [nicky-lenaers/ngx-scroll-to#135]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ x ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

No such listener / subscription

## Expected behavior

Would like to have a listener / subscription to inform when the animation finished, so that some actions can be performed after finishing.

## Minimal reproduction of the problem with instructions
No

## What is the motivation / use case for changing the behavior?

Need to know when the animation is finished so that some actions can be performed after finishing.

## Environment
Angular version 10.0.5

Your version of `@nicky-lenaers/ngx-scroll-to`:
9.0.0

Browser:
- [ x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

Would like to have an API for me to listen / subscribe to animation finish event.

**Comment by ajilderda** [comment]
@tenglongroy Do you mean you want to subscribe to the scroll finish event? In that case, this post might help:
https://github.com/nicky-lenaers/ngx-scroll-to/issues/53#issuecomment-478976758

**Comment by tenglongroy** [comment]
@ajilderda  Oh yes! that's the one! thank you!!!
