### ISSUE TITLE
angular 10+ support

### ISSUE THREAD

**Issue by igorlino** [nicky-lenaers/ngx-scroll-to#136]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

![image](https://user-images.githubusercontent.com/10480442/91944719-d3f33080-ecfe-11ea-829b-48469c9622ed.png)

## Expected behavior

No npm install warnings

## Minimal reproduction of the problem with instructions

1) update to angular 10.0.4 and latest ngx-scroll-to
2) npm install

## What is the motivation / use case for changing the behavior?

less messages, to increase confidence. Its only cosmetic, as it works with newer angular 10.0.4

## Environment

<pre><code>
Angular version: 10.0.4

Your version of `@nicky-lenaers/ngx-scroll-to`: latest

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 12.18.3
- Platform: Windows

Others:

</code></pre>

**Comment by daniel-seitz** [comment]
P.S. while you're at it, Angular 11 is coming up soon. What about making this package less restrictive and just specify the minimum version to avoid future issues like this. I mean something like:

```
"peerDependencies": {
    "@angular/common": ">=8.0.0",
    "@angular/core": ">=8.0.0",
    "tslib": "^1.10.0"
  }
```

Then, when something breaks, we could review this setting.

**Comment by smileLilith** [comment]
PR with the upgrade to Angular v10 https://github.com/nicky-lenaers/ngx-scroll-to/pull/138. Tagging @rafa-as 😄

**Comment by HarelM** [comment]
I would also like to see this getting in. Thanks!

**Comment by HarelM** [comment]
@nicky-lenaers can you update the dependencies to 11? I've tested this to work with angular 11 as well - I would like to avoid these warnings if possible... pretty please :-)

**Comment by rafa-as** [comment]
Hi there, I'm sorry for the delay, we will push the changes to make it work with Angular 11 ASAP.

**Comment by HarelM** [comment]
@rafa-as any updates on this? I haven't seen an update in npm...?

**Comment by D-Biela** [comment]
Still not updated... I guess we have to use an other package. I do not want to run npm install/update with the --force flag every time.

**Comment by csimpi** [comment]
ping

**Comment by HarelM** [comment]
@Jonnyprof @rafa-as Any chance to get this sorted out?

**Comment by HarelM** [comment]
@maintainers, any change to push this forward? it's been open for a long time now. It is currently the last package I get a warning about that is related to angular 12.
Simply change the dependencies to be >= 8.0 and add a note about using at your own risk, that's all, shouldn't take more than a few minutes...
Please, please, please...

**Comment by rbalet** [comment]
The repo doesn't seem to be maintained anymore....

**Comment by HarelM** [comment]
Yup, I'll probably copy the files here into my codebase and remove the reference... :-(

**Comment by igorlino** [comment]
:(  Angular 13.1 is out, and same story

**Comment by josh803316** [comment]
👍  Would be nice if this were updated.

```bash
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: @nicky-lenaers/ngx-scroll-to@9.0.0
npm ERR! Found: @angular/common@13.3.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"13.3.1" from the root project
npm ERR!   peer @angular/common@"^13.0.0 || ^14.0.0-0" from @angular/cdk@13.3.2
npm ERR!   node_modules/@angular/cdk
npm ERR!     @angular/cdk@"~13.3.2" from the root project
npm ERR!     peer @angular/cdk@"13.3.2" from @angular/material@13.3.2
npm ERR!     node_modules/@angular/material
npm ERR!       @angular/material@"~13.3.2" from the root project
npm ERR!   11 more (@angular/fire, @angular/forms, @angular/material, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.0.0 || ^9.0.0" from @nicky-lenaers/ngx-scroll-to@9.0.0
npm ERR! node_modules/@nicky-lenaers/ngx-scroll-to
npm ERR!   @nicky-lenaers/ngx-scroll-to@"^9.0.0" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: @angular/common@9.1.13
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^8.0.0 || ^9.0.0" from @nicky-lenaers/ngx-scroll-to@9.0.0
npm ERR!   node_modules/@nicky-lenaers/ngx-scroll-to
npm ERR!     @nicky-lenaers/ngx-scroll-to@"^9.0.0" from the root project
```

**Comment by igorlino** [comment]
:( Angular 14 is out

**Comment by sambernet** [comment]
Thanks to @rafa-as and @andreas-aeschlimann there is now some action again on this repo 🎉 

To link stuff together, maybe we can rename this issue to `Angular 10+ support` and close #150 as a duplicate @andreas-aeschlimann ?

Anyway, for anybody interested in the current progress, please also check the discussion in PR #164

**Comment by andreas-aeschlimann** [comment]
Closing in favor of #150

**Comment by rafa-as** [comment]
Angular 13 support it's released and the 14 it's on the way

**Comment by mmicheux** [comment]
Hi! Can this get Angular 11 support?

**Comment by tstackhouse** [comment]
The fork [@paulvmoreau/ngx-scroll-to](https://github.com/paulvmoreau/ngx-scroll-to) supports Angular 11, however neither supports Angular 12.  The latest updates only support 13 and 14, it makes the upgrade path very difficult.

**Comment by akaustav** [comment]
- For those looking for Angular 12 support specifically, I have created a fork at [@akaustav/ngx-scroll-to](https://github.com/akaustav/ngx-scroll-to).
- And published the corresponding [@akaustav/ngx-scroll-to](https://www.npmjs.com/package/@akaustav/ngx-scroll-to) npm package.
- I have also created a [Compatibility Table](https://github.com/akaustav/ngx-scroll-to#compatibility-table) to document compatibility between specific versions of the package and specific versions of Angular.
