### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by jamini87** [nicky-lenaers/ngx-scroll-to#150]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Your version of `@nicky-lenaers/ngx-scroll-to`:

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by igabesz** [comment]
In progress it seems: https://github.com/nicky-lenaers/ngx-scroll-to/pull/164

**Comment by andreas-aeschlimann** [comment]
Closing this issue in favor of #136

**Comment by akaustav** [comment]
- For those looking for Angular 12 support specifically, I have created a fork at [@akaustav/ngx-scroll-to](https://github.com/akaustav/ngx-scroll-to).
- And published the corresponding [@akaustav/ngx-scroll-to](https://www.npmjs.com/package/@akaustav/ngx-scroll-to) npm package.
- I have also created a [Compatibility Table](https://github.com/akaustav/ngx-scroll-to#compatibility-table) to document compatibility between specific versions of the package and specific versions of Angular.
