### ISSUE TITLE
Offset configuration acts as negative value when scrolling from bottom to top

### ISSUE THREAD

**Issue by AlexSapoznikov** [nicky-lenaers/ngx-scroll-to#29]
Hi!
When I am using `offset` option and the scrolling happens from the bottom to the top, it seems that the offset is acting as a negative value.

To clarify (using offset 200 for example):
* target.offsetTop > document.body.scrollTop - everything works fine, scrolls to target.offsetTop + 200px
* target.offsetTop < document.body.scrollTop - scrolls to target.offsetTop - 200px, instead of + 200px

I am not sure, is it happening only for me, but if it doesn't, would you please add `offsetTop` option to scroll configurations as well?

**Comment by nicky-lenaers** [comment]
Hi @AlexSapoznikov ,
Thank you for your issue submittance. Regarding your issue, I will mark this as a bug and will investigate to correct this behavior such that it behaves properly. The corrected code should allow you to use offset in case `target.offsetTop < document.body.scrollTop`, so I suppose you don't need an extra `offsetTop` in the config, right?

**Comment by AlexSapoznikov** [comment]
Hi @nicky-lenaers 
Yup, no need for extra `offsetTop` in the config. Thanks for investigating! :)
