### ISSUE TITLE
[Question] How to use service without event parameter?

### ISSUE THREAD

**Issue by igorissen** [nicky-lenaers/ngx-scroll-to#32]
Hi,

I want to use your library in my project but I saw that I need to provide an event parameter if I want to use the scroll service. Is there a way to bypass this?
Also I wonder if this library will work with my complex view.

```
Root
  - Header
  - Content
      - Carousel
      - Carousel
      - EPG <-- 24h programs
          - Program
          - Program <-- currently playing
          ...
```

I need to scroll to the currently playing program when the `Content` is loaded. How can I use `ngx-scroll-to` to achieve this?

**Comment by nicky-lenaers** [comment]
@igorissen Thank you for you issue. I'm aware of the fact that `event` should be left out of the service. This will be available in the near future.

Regarding the question if this plugin will work with your project, please provide an example fiddle or a link to your github repo.

Thank you!

**Comment by igorissen** [comment]
@nicky-lenaers Hope to see this feature soon.

Unfortunately, it's a client project and I can't show the code. I can just say that it is a view for an EPG. I can give the structure of my view with the initial actions.

```
Root
  - HeaderComponent (menu)
  - ContentComponent (link to menu selection)
      - ChannelsCarouselComponent (list of channels)
      - DatesCarouselComponent (list of dates)
      - EpgComponent (list of programs for the selected channel and date)
           - ProgramComponent (*ngFor on programs list)
```

- fetch channels list
- create dates list ([-7 days, today, +7 days])
- fetch programs for the selected channel and date (0 -> 23 hours)

After that, I need to use your library in the EpgComponent to scroll down to the currently playing program.

**Comment by daslaf** [comment]
Same here, I need to use the scroll service on some ReactiveForm FormControl value change.

**Comment by colthreepv** [comment]
Refers to #27, maybe close one of those?

**Comment by nicky-lenaers** [comment]
@colthreepv good point, so @daslaf and @igorissen see #27 for further updates. I expect this to land in october 2017 (so quite soon) as I'll be able to work on it from then on.
