### ISSUE TITLE
Unable to find Target Element - suppress this message when we don't care?

### ISSUE THREAD

**Issue by jessycormier** [nicky-lenaers/ngx-scroll-to#50]
## I'm submitting a request / bug
        const config: ScrollToConfigOptions = {
            container: '#some-wrapper',
            target: '#someIdNotOnPage
        };
        this.scrollToService.scrollTo(config).
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Feature request
[] Documentation issue or request
</code></pre>

## Current behavior
When trying to call the service to scroll to an element that does not exists, and there's no way to suppress the error being created in the console. It

## Expected behavior
Ability to capture and handle the error "Unable to find Target Element". A developer could handle this error how they want. do nothing or throw the issue.

## What is the motivation / use case for changing the behavior?
I am aware that the error will occur and it is normal behavior, I want to simply suppress the issue as in my case it is not.

**Comment by nicky-lenaers** [comment]
Hi @jessycormier , thank you for your feedback, it is much appreciated. I will take this issue into considering soon!

**Comment by nicky-lenaers** [comment]
@jessycormier You're now able to handle errors and suppress if needed, see [the updated README](https://github.com/nicky-lenaers/ngx-scroll-to#error-handling). Let me know if you need anything else!

Cheers 🍺
