### ISSUE TITLE
Detect if element is visible and abort scroll if it is

### ISSUE THREAD

**Issue by jredd** [nicky-lenaers/ngx-scroll-to#59]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
None

## Expected behavior
Some kind of option to prevent scrolling if the element is already visible within the parent container

## What is the motivation / use case for changing the behavior?
I have an element that any given time when the scroll function is triggered I don't currently know if it's visible or not. It doesn't make sense from a usability standpoint to have scrolling when it's already visible to the user. At least having the option to abort scrolling if visible would prevent animations from executing that provide no real help for the user.

<pre><code>
Angular version: 4.2.4

Browser:
- [x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX

**Comment by nicky-lenaers** [comment]
Hi @jredd , thank you for your issue. This module provides functionality of scrolling to a DOM element. As with any NPM module, it *should do one thing and one thing only*. Checking for an elements visibility in my opinion is therefore not a feature that should be placed in this module.

This module **does** provide a Service where you can programmatically trigger scroll-to animations. The Service should be sufficient for addiotional and/or conditional logic for the scroll-to animation. This is the place where you can implement a visibility check in your application logic. 

A nice way to do so is using the [Intersection Observer](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API). This way you can observe element you want to scroll to and, if already visible (a.k.a. *intersecting*), simply not trigger the scroll-to animation.

I like to hear your thoughts on this.

**Comment by nicky-lenaers** [comment]
@jredd Closing this, as the above comment answers your question. Thanks you for reporting this issue.
