### ISSUE TITLE
Scroll doesn't work with *ngIF block content on version 0.5.0 - 0.5.3

### ISSUE THREAD

**Issue by O-mkar** [nicky-lenaers/ngx-scroll-to#61]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Scroll doesn't scroll if the div is hidden under IF Block only on v0.5.0 but works fine on v0.4.0

## Expected behavior
It should scroll even if the block is hidden under *ngIf

## Minimal reproduction of the problem with instructions
Just try scrolling to Block hidden under *ngIf on v0.5.0

## What is the motivation / use case for changing the behavior?
It used everywhere 

## Environment

<pre><code>
Angular version: 5.0.2

Your version of `@nicky-lenaers/ngx-scroll-to`: 0.5.0

Browser:
- [ x] Chrome (desktop) version XX
- [ x] Chrome (Android) version XX
- [x ] Chrome (iOS) version XX
- [ x] Firefox version XX
- [x ] Safari (desktop) version XX
- [ x] Safari (iOS) version XX
- [x ] IE version XX
- [x ] Edge version XX
 
For Tooling issues:
- Node version: Latest
- Platform:  Mac

**Comment by O-mkar** [comment]
Found a temporary solution 

    `setTimeout(()=>{ 
        this.scrollservice.scrollTo(config)
       } , 2);`

**Comment by nicky-lenaers** [comment]
@O-mkar Yes, and this is by design. You need at least one Angular Lifecycle to evaulate an `*ngIf` and, after that, you can scroll to that element. A `setTimeout()` function does exactly that. It is a common problem and this module does not provide a solution to that. I will look into possibilities of fixing this, though I'm not sure yet whether this should be handled by the module or its users. Please share your thought.

**Comment by MikaAK** [comment]
@nicky-lenaers I'm having this problem even with using `setTimeout`

**Comment by nicky-lenaers** [comment]
@MikaAK You check [this Stackblitz example](https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to). The first page has a scroll animation with an `*ngIf` block to scroll to, which is working. The files that matter are [home.component.ts](https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to?file=src%2Fapp%2F%2Bhome%2Fhome.component.ts) and [home.component.html](https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to?file=src%2Fapp%2F%2Bhome%2Fhome.component.html). You can use that code for your case to make it work.

**Comment by americanslon** [comment]
I have the same issue. Anything new on this front?
The example from stackblitz doesn't seem to load by the way.
