### ISSUE TITLE
Stop loop code

### ISSUE THREAD

**Issue by arins** [nicky-lenaers/ngx-scroll-to#62]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

the animation never stops (tested with easeOutElastic). Side effects are for example arrow keys are not working for scrolling and also a interval is running which might slow down the webapp

## Expected behavior

the animation to stop ( the loop code to stop running)

## Minimal reproduction of the problem with instructions
I just installed it via npm and used the service 
Here is a debugger where the animation is done but the intervall is still running
![image](https://user-images.githubusercontent.com/1004420/35498640-6d40c9b6-04cf-11e8-980b-7f3855fc8a40.png)
Because the **this._position** is a float it never is exactly equal to **this._to + this._options.offset** the interval is not cleared. The stop code is never stopping to run even though scroll has reached its point.
DOES not happen if I use **easeInQuad** for example
<pre><code>
this.scrollToService.scrollTo({
					target: '#order-search-result-row-with-table',
					duration: 650,
					easing: 'easeOutElastic',
					offset: 0
				})
</code></pre>

## What is the motivation / use case for changing the behavior?
arrow keys are not working for scrolling and also a interval is running which might slow down the webapp

## Environment

<pre><code>
Angular version: 5.2.1

Your version of `@nicky-lenaers/ngx-scroll-to`:
0.5.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 
- Platform:  windows

Others:
nothing
</code></pre>

**Comment by nicky-lenaers** [comment]
Hi @arins , thank you for your issue. As I understand, this seems like a bug that needs to be fixed right away. I'm not sure when I have time for this, but you're very much welcome to submit a PR if possible!

**Comment by nicky-lenaers** [comment]
I applied a fix to this, but it is not sufficient. Reopening as it needs more investigation.

**Comment by arins** [comment]
If I have time I will look at it. I will make PR if that is the case

**Comment by nicky-lenaers** [comment]
I think I fixed this today. I was a combination of incorrect calculations and the float you described. You can check out [Release `0.5.3`](https://github.com/nicky-lenaers/ngx-scroll-to/releases/tag/0.5.3) and see if that fixes your case.

Thanks again for your issue submittance!

**Comment by arins** [comment]
Thanks I will check it out and let you know.

**Comment by arins** [comment]
@nicky-lenaers It works now the timeout is cleared. Thanks
