### ISSUE TITLE
 Scrolling does not work when inside an Angular Material Sidenav

### ISSUE THREAD

**Issue by AustinHatem** [nicky-lenaers/ngx-scroll-to#66]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
 Scrolling does not work when inside an Angular Material Sidenav.

## Expected behavior
For it to work.

## Minimal reproduction of the problem with instructions
Here is a stackblitz of it not working in Angualar Material Sidenav. if I take it out of the sidenav component then the scrolling will work.

https://stackblitz.com/edit/angular-37wifk

## What is the motivation / use case for changing the behavior?
I would like to use this product with Angular Materials 

Your version of `@nicky-lenaers/ngx-scroll-to`:
Using latest version

Browser:
- [X ] Chrome (desktop) version 63
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
</code></pre>

**Comment by yanis-git** [comment]
hi @AustinHatem i have notice on your demo is `.mat-drawer-content` who have `overflow: auto`. If you disable this property your are able to scroll to right position.

**Comment by yanis-git** [comment]
@ksonho i can't see any angular sidenav on your sample. Could you post us https://stackblitz.com/ reproductible issue ?

**Comment by ksonho** [comment]
yep, i am not using angular sidenav. I am using the form group and form control for it. maybe I need to create another issue?

**Comment by yanis-git** [comment]
I’am fine to keep same issue.

Could you post renderable sample of your issue. I will try my best to solve it.

**Comment by mehs2690** [comment]
When I open my page on my smartphone, the scroll works fine the first time, then it does not work anymore. I am using [ngx-scroll-to] to "ID's" in fixed navbar

**Comment by wduville** [comment]
I applied @yanis-git tips and it worked for me.
For my specific case I had also `.mat-tab-body-content ` and ` .mat-tab-body.mat-tab-body-active` to disable:

```
.mat-drawer-content, .mat-tab-body-content, .mat-tab-body.mat-tab-body-active {
    overflow: initial !important
}
```

**Comment by rafa-as** [comment]
Closed due inactivity
