### ISSUE TITLE
Scrolling is always interruptible by mousewheel events

### ISSUE THREAD

**Issue by luchianvictor** [nicky-lenaers/ngx-scroll-to#69]
## I'm submitting a...

<pre><code>
[x ] Documentation issue or request
</code></pre>

## Current behavior

When I set .scrollTo() , the scrolling animation can be interrupted by the user.
I tried setting event.preventDefault() and also setting the css property pointer-events: none

## Expected behavior

It should prevent any scrolling actions untill the animation completes

## Environment

<pre><code>
Angular version: 5.0.3

Your version of `@nicky-lenaers/ngx-scroll-to`: 0.6.0

Browser:
- [x ] Chrome (desktop) version 65

**Comment by nicky-lenaers** [comment]
Hi @luchianvictor , thank you for reporting your issue. This issue is, however, a dup of #8, so closing this. You can continue discussion there. Thank you.
