### ISSUE TITLE
How ngx-scroll-to can trigger scroll when page load?

### ISSUE THREAD

**Issue by vsok** [nicky-lenaers/ngx-scroll-to#72]
Here my code

```
<p><a [routerLink]="['/red']" [ngx-scroll-to]="'red'">Red</a> |
<a routerLink="/green" [ngx-scroll-to]="'green'">Green</a> |
<a routerLink="/blue" [ngx-scroll-to]="'blue'">Blue</a></p>

<div class="content">
        <blue-router></blue-router>
	<red-router></red-router>
	<green-router></green-router>
</div>
```

Is possible ngx-scroll-to can scroll when i enter "http://localhost:4200/blue"?
Is possible ngx-scroll-to can working back history?

**Comment by nicky-lenaers** [comment]
Hi @vsok , thank you for reporting your issue. Regarding your questions:

> Is possible ngx-scroll-to can scroll when i enter "http://localhost:4200/blue"?

Yes. You can do this using the service as described [here](https://www.npmjs.com/package/@nicky-lenaers/ngx-scroll-to#basic-usage---service-to-target). If you want it to trigger on page load, you can use the built-in `APP_INITIALIZER` from Angular ([docs](https://angular.io/api/core/APP_INITIALIZER)). Some tutorials on this can be found [here](https://www.intertech.com/Blog/angular-4-tutorial-run-code-during-app-initialization/), [here](https://hackernoon.com/hook-into-angular-initialization-process-add41a6b7e) and [here](https://stackoverflow.com/questions/41619443/how-to-call-an-rest-api-while-bootstrapping-angular-2-app).

> Is possible ngx-scroll-to can working back history?

Yes. You can use the built-in [`Location`](https://angular.io/api/common/Location) to listen to the *back* event on the browser. On this event, you should be able to use the service to trigger a scroll.

I hope this helps you out!
