### ISSUE TITLE
Safari always scrolls to top

### ISSUE THREAD

**Issue by ProjectWasp** [nicky-lenaers/ngx-scroll-to#73]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

JUST IN SAFARI, always scrolls to top of the page or doesn't work at all. (didn't test in iOS)

## Expected behavior
Should work the same as in Chrome

<pre><code>
Angular version: 5.2.3.

Your version of `@nicky-lenaers/ngx-scroll-to`: 3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ x ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version:  v8.9.4
- Platform:  MacOS
</code></pre>

**Comment by nicky-lenaers** [comment]
Hi @ProjectWasp , thank you for your issue. Please specify your Safari version so I can investigate. Thank you :)

**Comment by rafa-as** [comment]
I just checked that works as expected on Safari. Reopen it if you still have this issue.
