### ISSUE TITLE
Not working in Edge or IE

### ISSUE THREAD

**Issue by fbele** [nicky-lenaers/ngx-scroll-to#75]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report>
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
There isn't much to say. The module works flawlessly in Chrome and Firefox but in Edge and IE (11) doesn't react on click at all.

## Expected behavior
Working on all browsers.

## Environment

<pre><code>
Angular version: 4.4.6

Your version of `@nicky-lenaers/ngx-scroll-to`: v0.6.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ x ] IE version 11.371.16299.0
- [ x ] Edge version 41.16299.371.0
- [ x ] EdgeHTML version 16.16299

Probably also lesser versions of IE.
 
For Tooling issues:
- Node version: v8.9.1
- Platform:  Windows 10

</code></pre>

**Comment by GregSithole** [comment]
Hey

I'm using Microsoft Edge 41.16299.371.0 (Same as You) and it does work but I'll be honest when I say it has a bug on my side... so when I click on the Nav Item, it bounces to the top of the page and then navigates to where it needs to go. 

Just adding additional info to your Issue

**Comment by nicky-lenaers** [comment]
@fbele @GregSithole Thank you guys for reporting this. Do you mind setting up a small Stackblitz. There is a template you can use [here](https://stackblitz.com/github/nicky-lenaers/ngx-scroll-to).

**NOTE**

When I run this demo from the Stackblitz template in Edge, it all works fine. For now, I can't reproduce. I'll investigate once you have the Stackblitz. Thanks again!

**Comment by GregSithole** [comment]
@nicky-lenaers I create another Stackblitz for you to check out... I'm pretty much still having that issue... 
Here's my stackblitz: https://stackblitz.com/edit/angular-7udsyf

**Comment by juarvarfedev** [comment]
@nicky-lenaers, just to let you know, I've found and issue when testing in IE11. It doesn't scroll if you have the parent element css property set to **overflow-y:hidden**, I've changed to **overflow-y:scroll** and it worked fine.

**Comment by rafa-as** [comment]
I just checked that works on IE11 and Edge.
