### ISSUE TITLE
Make compatible with Angular 6

### ISSUE THREAD

**Issue by Hainesy** [nicky-lenaers/ngx-scroll-to#82]
`ng update rxjs`

`Package "@nicky-lenaers/ngx-scroll-to" has an incompatible peer dependency to "rxjs" (requires "^5.4.2", would install "6.1.0").`

**Comment by nicky-lenaers** [comment]
Hi @Hainesy , I am working on this already. There are some other issues with priority, but this will soon be implemented. Thank you for reporting!

**Comment by DavidBowdoin** [comment]
In case this helps anyone, here are the changes I made to make ngx-scroll-to work with rxjs 6.1.0

In scroll-to.service.d.ts  I replaced line 1 with:
`import { Observable } from 'rxjs';`

in ngx-scroll-to.es5.js I replaced the three lines at 4,5,6  with these 2 lines:
```
import { Observable as Observable$1 } from 'rxjs';
import { ReplaySubject as ReplaySubject$1 } from 'rxjs';
```
