### ISSUE TITLE
Add scroll support to elements with "overflow" property set to "overlay"

### ISSUE THREAD

**Issue by Pedrozxcv** [nicky-lenaers/ngx-scroll-to#87]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[] Bug report 
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Scroll is not working when the scrollable element has "overflow: overlay". From a quick peek on the code, I noticed that only "overflow:auto" and "overflow:scroll" are being checked.

`const overflowRegex: RegExp = /(auto|scroll)/;` in `scroll-to.service.ts`

## Expected behavior
Scroll should work to a scrollable element that has "overflow:overlay".

**Comment by nicky-lenaers** [comment]
@Pedrozxcv Thank you for you issue. I will look into this shortly. Stay tuned!
