### ISSUE TITLE
@nicky-lenaers/ngx-scroll-to@"<1" not working

### ISSUE THREAD

**Issue by augustovandyk** [nicky-lenaers/ngx-scroll-to#91]
## I'm submitting 
A npm install issue for ngx-scroll-to

## Current behavior
When using  npm install @nicky-lenaers/ngx-scroll-to@"<1" it replies with the following: 
"The system cannot find the file specified."

## Expected behavior
For npm install @nicky-lenaers/ngx-scroll-to to work for angular versions before 6

## Environment
Angular version: 
angular/cli: 1.7.1
angular-devkit/build-optimizer: 0.3.2
angular-devkit/core: 0.3.2
angular-devkit/schematics: 0.3.2
ngtools/json-schema: 1.2.0
ngtools/webpack: 1.10.1
schematics/angular: 0.3.2
schematics/package-update: 0.3.2
typescript: 2.5.3
 
For Tooling issues:
- Node version: 5.6.0
- Platform:  Windows

Other: 
This is the first issue I am reporting so forgive me for any mistakes. I did check if the issue is already published but could not find anything. To me it seems as though older versions do not exist.

**Comment by Shane-E** [comment]
The npm package shows there have been 27 versions published at this time of writing. The latest version before 1.0.0 is 0.6.1, so I would suggest trying `npm i @nicky-lenaers/ngx-scroll-to@0.6.1`

**Comment by augustovandyk** [comment]
@Shane-E Thanks a lot. That works great!
