### ISSUE TITLE
i canot scroll to id in ngfor but href can scroll. 

### ISSUE THREAD

**Issue by ardcsr** [nicky-lenaers/ngx-scroll-to#92]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

cannot use ngx-scroll-to to scroll to id in ngFor in angular 6 but href can scroll.

## Environment

<pre><code>
Angular version: 6

Your version of `@nicky-lenaers/ngx-scroll-to`:1.00

 

</code></pre>

**Comment by KlausEichinger** [comment]
On a dynamic built item list (*ngFor):

<button [ngx-scroll-to]="'#H'">ngx-scroll-to #H</button>
<button [ngx-scroll-to]="'H'">ngx-scroll-to H</button>
<a [ngx-scroll-to]="'#H'">ngx-scroll-to #H</a>
<a [ngx-scroll-to]="'H'">ngx-scroll-to H</a>

works like expected

**Comment by ardcsr** [comment]
it not work. it scroll to top only.
 <a [ngx-scroll-to]="'SUB'" style="cursor: pointer;">
<a [ngx-scroll-to]="'#SUB'" style="cursor: pointer;">

**Comment by KlausEichinger** [comment]
Show more code please

**Comment by ardcsr** [comment]
loop
<div *ngFor="let contentSup of modelShow; let index=index" >
        <div [id]="'SUB'+index">.........</div>
</div>


<a [ngx-scroll-to]="'#SUB0'" style="cursor: pointer;">Contact us</a>

**Comment by ardcsr** [comment]
Ho no! it my bad. it have id='SUB1' in my code. i don't know why another id not works . When i delete id='SUB1', everything is work.
Thanks @KlausEichinger
