### ISSUE TITLE
Angular6 ngrx6 rxjs6 compatability issues

### ISSUE THREAD

**Issue by sssalib42** [nicky-lenaers/ngx-scroll-to#97]
After upgrading to rxjs 6, I can't finish my upgrade process, specifically the very last step, which is to remove the rxjs-compat library, because ngrx-scroll-to is still using rxjs5 syntax.

Here is a github issue, explaining the problem I'm facing because ngrx-scroll-to isn't up to date:
ReactiveX/rxjs#3654

Here is a useful page including the rxjs 6 upgrade instruction:
https://auth0.com/blog/whats-new-in-rxjs-6/

**Comment by nicky-lenaers** [comment]
Hi @sssalib42, I've been away for a little while, picking up development on this repo from this point forward again. Your PR will be very welcome!

**Comment by sssalib42** [comment]
@nicky-lenaers , I just noticed that you have already done the good work of upgrading the code in the latest release 1.0.0.

My errors were resolved by updating my package.json version of ngx-scroll-to from "^0.6.0" to "^1.0.0".

Thank you. 

Please feel free to close the issue.
